version: '3'

services:
  jenkins:
    image: jenkins/ssh-agent:alpine-jdk17
    container_name: jenkins
    ports:
      - "8092:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:

